### ISSUE TITLE
Make all plotting dependencies optional

### ISSUE THREAD

**Issue by ocefpaf** [ioos/gliderpy#117]
We should make all plotting dependencies, like pandas_flavor, matplotlib, and cartopy (any other?), optional as a plotting extras.

@FloraSauerbronn this would require you to edit the `requirements.txt` file, to remove any plotting dependencies that may be listed there, and add a new entry in the `pyproject.toml` like:

```toml
[project.optional-dependencies]
plotting = [list_the_dependencies_here ]
```

Can you tackle that?
